/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as LostFriendRouteImport } from './routes/lost-friend'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CrowdRouteImport } from './routes/crowd'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFriendRoute = LostFriendRouteImport.update({
  id: '/lost-friend',
  path: '/lost-friend',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdRoute = CrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crowd': typeof CrowdRoute
  '/emergency': typeof EmergencyRoute
  '/lost-friend': typeof LostFriendRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/translate': typeof TranslateRoute
  '/wallet': typeof WalletRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crowd': typeof CrowdRoute
  '/emergency': typeof EmergencyRoute
  '/lost-friend': typeof LostFriendRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/translate': typeof TranslateRoute
  '/wallet': typeof WalletRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crowd': typeof CrowdRoute
  '/emergency': typeof EmergencyRoute
  '/lost-friend': typeof LostFriendRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/translate': typeof TranslateRoute
  '/wallet': typeof WalletRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/crowd'
    | '/emergency'
    | '/lost-friend'
    | '/map'
    | '/marketplace'
    | '/nearby'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/translate'
    | '/wallet'
    | '/marketplace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/crowd'
    | '/emergency'
    | '/lost-friend'
    | '/map'
    | '/marketplace'
    | '/nearby'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/translate'
    | '/wallet'
    | '/marketplace/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/crowd'
    | '/emergency'
    | '/lost-friend'
    | '/map'
    | '/marketplace'
    | '/nearby'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/translate'
    | '/wallet'
    | '/marketplace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CrowdRoute: typeof CrowdRoute
  EmergencyRoute: typeof EmergencyRoute
  LostFriendRoute: typeof LostFriendRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  NearbyRoute: typeof NearbyRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TranslateRoute: typeof TranslateRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-friend': {
      id: '/lost-friend'
      path: '/lost-friend'
      fullPath: '/lost-friend'
      preLoaderRoute: typeof LostFriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd': {
      id: '/crowd'
      path: '/crowd'
      fullPath: '/crowd'
      preLoaderRoute: typeof CrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CrowdRoute: CrowdRoute,
  EmergencyRoute: EmergencyRoute,
  LostFriendRoute: LostFriendRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  NearbyRoute: NearbyRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TranslateRoute: TranslateRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
